
final List<String> motivationalQuotes = [
  "Believe you can and you're halfway there.",
  "Push yourself, because no one else is going to do it for you.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Success is not for the lazy.",
  "The secret of getting ahead is getting started.",
  "Dream it. Wish it. Do it.",
  "Great things never come from comfort zones.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "It always seems impossible until it’s done.",
  "Your limitation—it’s only your imagination.",
  "Push harder than yesterday if you want a different tomorrow.",
  "Little things make big days.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The way to get started is to quit talking and begin doing.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Do something today that your future self will thank you for.",
  "Doubt kills more dreams than failure ever will.",
  "Discipline is the bridge between goals and accomplishment.",
  "Work hard in silence, let your success be the noise.",
  "Success doesn’t just find you. You have to go out and get it.",
  "If you get tired, learn to rest, not to quit.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The key to success is to focus on goals, not obstacles.",
  "Start where you are. Use what you have. Do what you can.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Don’t limit your challenges. Challenge your limits.",
  "Every accomplishment starts with the decision to try.",
];
